### PR TITLE
Pierce branch

### PR DESCRIPTION
**Pull request by pkeane1**
Pushing working YELP API to master

### CODE REVIEW

**Review by MiaTee — APPROVED** [review]

**Review by charissafajardo — CHANGES_REQUESTED** [review]
css changes

**Review by MiaTee — COMMENTED** [review]
Please remove the empty styles.css file it is conflicting with Charlie's change.

**Review by MiaTee — CHANGES_REQUESTED** [review]
Please remove empty styles.css. It will overwrite Charlie's changes

**Review by kev9090 — CHANGES_REQUESTED** [review]
conflicted

**Pull request closed without merging**
